# backend/app/services/professional_judgment_constants.py
from __future__ import annotations

SIGNAL_PRIORITY_DEFAULT = (
    "contradiction",
    "blocking_issue",
    "critical_missing",
    "urgency",
    "practical_risk",
    "actionability",
    "base_strength",
)

SIGNAL_PRIORITY = SIGNAL_PRIORITY_DEFAULT

SIGNAL_PRIORITY_BY_DOMAIN = {
    "familia": SIGNAL_PRIORITY_DEFAULT,
    "alimentos": SIGNAL_PRIORITY_DEFAULT,
    "laboral": (
        "urgency",
        "practical_risk",
        "contradiction",
        "blocking_issue",
        "critical_missing",
        "actionability",
        "base_strength",
    ),
}

SIGNAL_PRIORITY_RANK = {
    signal: index
    for index, signal in enumerate(SIGNAL_PRIORITY)
}

URGENCY_SCORE_HIGH = 85
URGENCY_SIGNAL_SCORE = 95

PRACTICAL_RISK_SCORE_HIGH = 75
PRACTICAL_RISK_DETECTED_BONUS = 20
PRACTICAL_RISK_CONTRADICTION_BONUS = 25
PRACTICAL_RISK_BLOCKING_BONUS = 20
PRACTICAL_RISK_CRITICAL_GAP_BONUS = 15
PRACTICAL_RISK_IMPORTANT_GAP_BONUS = 8
PRACTICAL_RISK_BLOCKED_STATUS_BONUS = 10

ACTION_READY_SCORE_MIN = 72
BASE_STRENGTH_FOR_ACTION_READY = 45
BASE_STRENGTH_FOR_GUARDED_ACTION = 45
BASE_STRENGTH_SOLID = 60

CONFIDENCE_BASE_SCORE = 30
CONFIDENCE_HIGH_BONUS = 25
CONFIDENCE_MEDIUM_BONUS = 12
CONFIDENCE_SCORE_WEIGHT = 20
READINESS_HIGH_BONUS = 15
READINESS_MEDIUM_BONUS = 8
CLOSURE_HIGH_BONUS = 8
EVIDENCE_PRESENT_BONUS = 6

ACTION_CANDIDATE_BONUS = 25
PROGRESS_READY_BONUS = 20
NEXT_STEP_ACTION_BONUS = 20
ACTION_FIRST_STRATEGY_BONUS = 10
ACTION_READY_CONFIDENCE_WEIGHT = 10

CRITICAL_MISSING_SIGNAL_WEIGHT = 35
CONTRADICTION_SIGNAL_WEIGHT = 50
BLOCKING_ISSUE_SIGNAL_WEIGHT = 45

DOMINANCE_HIGH_SCORE = 80
DOMINANCE_MEDIUM_SCORE = 55
DECISION_CONFIDENCE_HIGH_SCORE = 78
DECISION_CONFIDENCE_MEDIUM_SCORE = 52
DECISION_CONFLICT_HIGH_GAP = 10
DECISION_CONFLICT_MEDIUM_GAP = 24
