from __future__ import annotations


META_HISTORY_LIMIT = 120
META_MIN_HISTORY_CYCLES = 4
META_MIN_KNOWN_OUTCOMES = 2
META_STRONG_HISTORY_CYCLES = 8
META_STRONG_KNOWN_OUTCOMES = 5
META_MIN_MODE_CYCLES = 3
META_MIN_MODE_KNOWN_OUTCOMES = 2
META_MIN_CONTEXT_RECORDS = 2
META_MIN_CONTEXT_WEIGHTED_RECORDS = 1.2

META_HIGH_UNKNOWN_OUTCOME_RATE = 0.6
META_HIGH_CONFIDENCE_BAD_OUTCOME_RATE = 0.25
META_PARAMETER_SUCCESS_FAVOR_RATE = 0.7
META_PARAMETER_FAILURE_BLOCK_RATE = 0.6
META_PARAMETER_ROLLBACK_BLOCK_RATE = 0.25
META_MODE_FAILURE_DOWNGRADE_RATE = 0.5
META_MODE_ROLLBACK_DOWNGRADE_RATE = 0.2
META_MODE_CONSERVATIVE_RATE = 0.6

META_BUCKET_LOW = "low"
META_BUCKET_MEDIUM = "medium"
META_BUCKET_HIGH = "high"

META_CONTEXT_STABLE = "stable"
META_CONTEXT_FRAGILE = "fragile"
META_CONTEXT_ROLLBACK_PRESSURE = "rollback_pressure"
META_CONTEXT_DRIFT = "drift_context"
META_CONTEXT_LOW_EVIDENCE = "low_evidence_context"

META_TEMPORAL_WEIGHT_RECENT_HOURS = 24
META_TEMPORAL_WEIGHT_RECENT = 1.0
META_TEMPORAL_WEIGHT_WEEK_HOURS = 168
META_TEMPORAL_WEIGHT_WEEK = 0.5
META_TEMPORAL_WEIGHT_OLD = 0.2

META_CONFIDENCE_LOW = 0.4
META_CONFIDENCE_MEDIUM = 0.65
META_CONFIDENCE_HIGH = 0.8

MODE_ORDER = {
    "conservative": 0,
    "balanced": 1,
    "aggressive": 2,
}
