"""
AILEX -- Action taxonomy

Centraliza la definicion de acciones juridicas/procesales para que el
clasificador mantenga la logica separada de los datos juridicos.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class ActionTaxonomyEntry:
    action_slug: str
    action_label: str
    legal_intent: str
    forum: str
    process_type: str
    domain: str
    patterns: tuple[str, ...] = ()
    semantic_aliases: tuple[str, ...] = ()
    retrieval_queries: tuple[str, ...] = ()
    priority_articles: tuple[dict[str, str], ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)
    weighted_signals: dict[str, float] = field(default_factory=dict)
    required_signal_groups: tuple[tuple[str, ...], ...] = ()
    minimum_score: float = 0.0


DIVORCE_PRIORITY_ARTICLES: tuple[dict[str, str], ...] = (
    {"source_id": "codigo_civil_comercial", "article": "435"},
    {"source_id": "codigo_civil_comercial", "article": "437"},
    {"source_id": "codigo_civil_comercial", "article": "438"},
    {"source_id": "codigo_civil_comercial", "article": "439"},
    {"source_id": "codigo_civil_comercial", "article": "440"},
    {"source_id": "codigo_civil_comercial", "article": "441"},
    {"source_id": "codigo_civil_comercial", "article": "717"},
    {"source_id": "codigo_civil_comercial", "article": "721"},
)

CHILD_SUPPORT_PRIORITY_ARTICLES: tuple[dict[str, str], ...] = (
    {"source_id": "codigo_civil_comercial", "article": "658"},
    {"source_id": "codigo_civil_comercial", "article": "659"},
    {"source_id": "codigo_civil_comercial", "article": "660"},
    {"source_id": "codigo_civil_comercial", "article": "661"},
    {"source_id": "codigo_civil_comercial", "article": "662"},
    {"source_id": "codigo_civil_comercial", "article": "663"},
    {"source_id": "codigo_civil_comercial", "article": "664"},
    {"source_id": "codigo_civil_comercial", "article": "669"},
)

SUCCESSION_PRIORITY_ARTICLES: tuple[dict[str, str], ...] = (
    {"source_id": "codigo_civil_comercial", "article": "2336"},
    {"source_id": "codigo_civil_comercial", "article": "2337"},
    {"source_id": "codigo_civil_comercial", "article": "2338"},
    {"source_id": "codigo_civil_comercial", "article": "2340"},
    {"source_id": "codigo_civil_comercial", "article": "2341"},
    {"source_id": "codigo_civil_comercial", "article": "2342"},
    {"source_id": "codigo_civil_comercial", "article": "2343"},
)

DIVORCE_TERMINATION_SIGNALS: tuple[str, ...] = (
    "divorcio",
    "divorciarse",
    "divorciarme",
    "divorciar",
    "me quiero divorciar",
    "quiero divorciarme",
    "quiero el divorcio",
    "separarse",
    "separacion",
    "disolver",
    "disolucion",
    "terminar",
    "poner fin",
    "poner fin a su relacion",
    "terminar el matrimonio",
    "vinculo matrimonial",
    "no quiere continuar",
)

DIVORCE_RELATIONSHIP_SIGNALS: tuple[str, ...] = (
    "matrimonio",
    "vinculo matrimonial",
    "conyuge",
    "conyuges",
    "esposo",
    "esposa",
    "esposos",
    "esposas",
    "casados",
    "casadas",
)

DIVORCE_JOINT_SIGNALS: tuple[str, ...] = (
    "ambos",
    "ambas",
    "ambas partes",
    "dos personas",
    "dos conyuges",
    "esposos",
    "esposas",
    "matrimonio",
    "conjunto",
    "conjunta",
    "peticion conjunta",
    "presentacion conjunta",
    "mutuo acuerdo",
    "comun acuerdo",
    "bilateral",
)

DIVORCE_UNILATERAL_SIGNALS: tuple[str, ...] = (
    "yo quiero divorciarme",
    "yo si",
    "uno solo",
    "uno de los conyuges",
    "mi esposa no quiere",
    "mi esposo no quiere",
    "no quiere divorciarse",
    "no quiere el divorcio",
)

CHILD_SUPPORT_SIGNALS: tuple[str, ...] = (
    "alimentos",
    "cuota alimentaria",
    "cuota alimentaria provisoria",
    "alimentos provisorios",
    "prestacion alimentaria",
    "cuota",
    "hijo",
    "hija",
    "hijos",
    "padre",
    "madre",
    "progenitor",
    "progenitora",
    "no paga",
    "no cumple",
    "aumento de cuota",
    "reduccion de cuota",
)

SUCCESSION_SIGNALS: tuple[str, ...] = (
    "sucesion",
    "herencia",
    "heredero",
    "herederos",
    "causante",
    "declaratoria",
    "ab intestato",
    "murio",
    "fallecio",
    "fallecimiento",
    "padre",
    "madre",
)

ACTION_TAXONOMY: tuple[ActionTaxonomyEntry, ...] = (
    ActionTaxonomyEntry(
        action_slug="divorcio_mutuo_acuerdo",
        action_label="Divorcio por mutuo acuerdo",
        legal_intent="disolucion_vinculo_matrimonial",
        forum="familia",
        process_type="voluntario",
        domain="family",
        patterns=(
            "divorcio de comun acuerdo",
            "divorcio por mutuo acuerdo",
            "divorcio mutuo acuerdo",
            "divorcio bilateral",
            "peticion conjunta de divorcio",
            "presentacion conjunta de divorcio",
            "quieren divorciarse",
            "se quieren divorciar",
            "ambos quieren divorciarse",
            "ambas quieren divorciarse",
            "dos personas quieren divorciarse",
            "dos conyuges quieren divorciarse",
            "convenio regulador",
            "terminar el matrimonio",
            "disolver el vinculo matrimonial",
            "poner fin a su relacion",
            "el matrimonio no quiere continuar",
        ),
        semantic_aliases=(
            "divorcio mutuo acuerdo",
            "divorcio de comun acuerdo",
            "divorcio bilateral",
            "peticion conjunta de divorcio",
            "presentacion conjunta con convenio regulador",
            "propuesta reguladora del divorcio",
        ),
        retrieval_queries=(
            "divorcio a peticion de ambos conyuges convenio regulador",
            "requisitos y procedimiento del divorcio convenio regulador",
            "proceso de divorcio presentacion conjunta competencia medidas provisionales",
        ),
        priority_articles=DIVORCE_PRIORITY_ARTICLES,
        metadata={
            "family_matter": "divorcio",
            "expected_normative_sources": ["codigo_civil_comercial"],
        },
        weighted_signals={
            "divorcio": 2.4,
            "divorciarse": 2.4,
            "separarse": 1.9,
            "separacion": 1.7,
            "disolver": 1.8,
            "disolucion": 1.6,
            "terminar": 1.4,
            "poner fin": 1.8,
            "poner fin a su relacion": 2.0,
            "terminar el matrimonio": 2.3,
            "matrimonio": 1.5,
            "vinculo matrimonial": 2.2,
            "conyuge": 1.3,
            "conyuges": 1.6,
            "esposo": 1.2,
            "esposa": 1.2,
            "esposos": 1.6,
            "esposas": 1.6,
            "casados": 1.4,
            "casadas": 1.4,
            "ambos": 1.2,
            "ambas": 1.2,
            "ambas partes": 1.5,
            "dos personas": 1.1,
            "dos conyuges": 1.4,
            "conjunto": 1.0,
            "conjunta": 1.0,
            "peticion conjunta": 1.7,
            "presentacion conjunta": 1.7,
            "mutuo acuerdo": 2.4,
            "comun acuerdo": 2.3,
            "bilateral": 1.7,
            "convenio regulador": 2.1,
            "no quiere continuar": 2.0,
        },
        required_signal_groups=(
            DIVORCE_TERMINATION_SIGNALS,
            DIVORCE_JOINT_SIGNALS,
        ),
        minimum_score=4.2,
    ),
    ActionTaxonomyEntry(
        action_slug="divorcio_unilateral",
        action_label="Divorcio unilateral",
        legal_intent="disolucion_vinculo_matrimonial",
        forum="familia",
        process_type="contencioso_inicial",
        domain="family",
        patterns=(
            "mi esposa no quiere divorciarse pero yo si",
            "mi esposo no quiere divorciarse pero yo si",
            "quiero divorciarme pero mi esposa no",
            "quiero divorciarme pero mi esposo no",
            "uno solo quiere divorciarse",
            "divorcio unilateral",
        ),
        semantic_aliases=(
            "divorcio unilateral",
            "divorcio a peticion de uno de los conyuges",
            "divorcio cuando la otra parte no quiere",
        ),
        retrieval_queries=(
            "divorcio a peticion de uno de los conyuges propuesta reguladora",
            "divorcio unilateral ccyc art 437 438 439 717",
            "divorcio medidas provisionales competencia ultimo domicilio conyugal",
        ),
        priority_articles=DIVORCE_PRIORITY_ARTICLES,
        metadata={
            "family_matter": "divorcio",
            "expected_normative_sources": ["codigo_civil_comercial"],
            "variant": "unilateral",
        },
        weighted_signals={
            "divorcio": 2.5,
            "divorciarse": 2.5,
            "separarse": 1.8,
            "esposa": 1.4,
            "esposo": 1.4,
            "conyuge": 1.3,
            "conyuges": 1.5,
            "yo quiero divorciarme": 2.6,
            "yo si": 1.8,
            "uno solo": 2.2,
            "uno de los conyuges": 2.2,
            "mi esposa no quiere": 2.5,
            "mi esposo no quiere": 2.5,
            "no quiere divorciarse": 2.7,
            "no quiere el divorcio": 2.4,
            "quiero divorciarme": 2.4,
            "quiero el divorcio": 2.3,
            "matrimonio": 1.2,
            "vinculo matrimonial": 1.6,
        },
        required_signal_groups=(
            DIVORCE_TERMINATION_SIGNALS,
            DIVORCE_UNILATERAL_SIGNALS,
        ),
        minimum_score=4.0,
    ),
    ActionTaxonomyEntry(
        action_slug="alimentos_hijos",
        action_label="Alimentos para hijos",
        legal_intent="reclamo_alimentos_hijos",
        forum="familia",
        process_type="contencioso_sumario",
        domain="family",
        patterns=(
            "alimentos",
            "cuota alimentaria",
            "cuota alimentaria provisoria",
            "alimentos provisorios",
            "alimentos hijos",
            "aumento de cuota",
            "reduccion de cuota",
            "aumento de cuota alimentaria",
            "reduccion de cuota alimentaria",
            "el padre de mi hijo no paga alimentos",
            "la madre de mi hijo no paga alimentos",
            "no paga alimentos",
            "cuota alimentaria para mi hijo",
            "demanda de alimentos para mi hijo",
            "reclamar alimentos para mi hijo",
        ),
        semantic_aliases=(
            "alimentos para hijos",
            "cuota alimentaria de hijo menor",
            "cuota alimentaria provisoria",
            "alimentos provisorios",
            "demanda de alimentos contra progenitor incumplidor",
            "aumento de cuota alimentaria",
            "reduccion de cuota alimentaria",
        ),
        retrieval_queries=(
            "alimentos hijos progenitor incumplidor legitimacion monto retroactividad",
            "ccyc alimentos hijos articulos 658 659 660 661 662 663 664 669",
            "demanda de alimentos hijo menor padre no paga",
            "cuota alimentaria provisoria hijo menor necesidades",
            "alimentos provisorios medida cautelar urgencia",
        ),
        priority_articles=CHILD_SUPPORT_PRIORITY_ARTICLES,
        metadata={
            "family_matter": "alimentos_hijos",
            "expected_normative_sources": ["codigo_civil_comercial"],
        },
        weighted_signals={
            "alimentos": 2.8,
            "cuota alimentaria": 2.7,
            "cuota alimentaria provisoria": 3.0,
            "alimentos provisorios": 2.9,
            "prestacion alimentaria": 2.0,
            "cuota": 1.6,
            "provisoria": 1.4,
            "provisorio": 1.4,
            "provisorios": 1.4,
            "hijo": 1.9,
            "hija": 1.9,
            "hijos": 1.9,
            "padre": 1.4,
            "madre": 1.4,
            "progenitor": 1.5,
            "progenitora": 1.5,
            "no paga": 2.2,
            "no cumple": 1.8,
            "deuda alimentaria": 2.2,
            "demanda de alimentos": 2.5,
            "reclamar alimentos": 2.2,
            "aumento de cuota": 2.4,
            "reduccion de cuota": 2.4,
            "aumento": 1.2,
            "reduccion": 1.2,
            "incumplimiento": 1.8,
        },
        required_signal_groups=(
            CHILD_SUPPORT_SIGNALS,
        ),
        minimum_score=2.6,
    ),
    ActionTaxonomyEntry(
        action_slug="sucesion_ab_intestato",
        action_label="Sucesion ab intestato",
        legal_intent="apertura_sucesion_intestada",
        forum="civil",
        process_type="voluntario_sucesorio",
        domain="civil",
        patterns=(
            "murio mi padre y queremos iniciar la sucesion",
            "iniciar la sucesion",
            "abrir la sucesion",
            "sucesion ab intestato",
            "declaratoria de herederos",
            "mi padre murio y queremos hacer la sucesion",
        ),
        semantic_aliases=(
            "sucesion intestada",
            "apertura de sucesion",
            "declaratoria de herederos",
        ),
        retrieval_queries=(
            "apertura de sucesion intestada declaratoria de herederos ccyc",
            "ccyc sucesion causa de muerte apertura administracion hereditaria",
            "documentacion para iniciar sucesion ab intestato",
        ),
        priority_articles=SUCCESSION_PRIORITY_ARTICLES,
        metadata={
            "civil_matter": "sucesion",
            "expected_normative_sources": ["codigo_civil_comercial"],
            "variant": "ab_intestato",
        },
        weighted_signals={
            "sucesion": 2.7,
            "herencia": 2.2,
            "heredero": 1.8,
            "herederos": 1.8,
            "causante": 1.9,
            "declaratoria": 2.3,
            "ab intestato": 2.8,
            "murio": 2.1,
            "fallecio": 2.1,
            "fallecimiento": 1.8,
            "padre": 1.4,
            "madre": 1.4,
            "iniciar la sucesion": 2.5,
            "abrir la sucesion": 2.5,
        },
        required_signal_groups=(
            SUCCESSION_SIGNALS,
        ),
        minimum_score=4.0,
    ),
    ActionTaxonomyEntry(
        action_slug="divorcio",
        action_label="Divorcio",
        legal_intent="disolucion_vinculo_matrimonial",
        forum="familia",
        process_type="contencioso_o_voluntario",
        domain="family",
        patterns=(
            "divorcio",
            "divorciarse",
            "divorciarme",
            "divorciar",
            "peticionar el divorcio",
            "pedir el divorcio",
            "quiero divorciarme",
            "quiero el divorcio",
            "me quiero divorciar",
            "quiero separarme de mi esposa",
            "quiero separarme de mi esposo",
            "separarse legalmente",
            "disolver el matrimonio",
        ),
        semantic_aliases=(
            "divorcio",
            "proceso de divorcio",
            "peticion judicial de divorcio",
            "quiero divorciarme",
            "me quiero divorciar",
            "quiero el divorcio",
        ),
        retrieval_queries=(
            "divorcio legitimacion requisitos y procedimiento",
            "divorcio convenio regulador compensacion economica competencia",
            "divorcio a peticion de uno o ambos conyuges propuesta reguladora competencia",
        ),
        priority_articles=DIVORCE_PRIORITY_ARTICLES,
        metadata={
            "family_matter": "divorcio",
            "expected_normative_sources": ["codigo_civil_comercial"],
        },
        weighted_signals={
            "divorcio": 2.6,
            "divorciarse": 2.6,
            "divorciarme": 2.8,
            "divorciar": 2.0,
            "quiero divorciarme": 3.0,
            "quiero el divorcio": 2.9,
            "me quiero divorciar": 3.0,
            "quiero separarme de mi esposa": 2.8,
            "quiero separarme de mi esposo": 2.8,
            "separarse": 2.0,
            "separacion": 1.7,
            "disolver": 1.8,
            "disolucion": 1.6,
            "terminar": 1.2,
            "poner fin": 1.5,
            "terminar el matrimonio": 2.0,
            "matrimonio": 1.3,
            "vinculo matrimonial": 2.0,
            "conyuge": 1.1,
            "conyuges": 1.4,
            "esposo": 1.0,
            "esposa": 1.0,
            "esposos": 1.3,
            "esposas": 1.3,
            "convenio regulador": 1.0,
        },
        required_signal_groups=(
            DIVORCE_TERMINATION_SIGNALS,
        ),
        minimum_score=2.6,
    ),
)

TAXONOMY_BY_ACTION: dict[str, ActionTaxonomyEntry] = {
    entry.action_slug: entry for entry in ACTION_TAXONOMY
}
